### PR TITLE
This should fix build issues

### PR DESCRIPTION
**Pull request by edisile**
Had some issues like #14 building on Arch Linux and using Python 3.7, this fixed them

### CODE REVIEW

**Comment by n-peugnet** [comment]
Hi, I'm really interested by this lib, and I just wanted to add that indeed, this branch [managed to build using python3](https://travis-ci.org/n-peugnet/music-player-core/builds/637517450).

Is there plans on merging this and release a version that works with python3 ?

**Comment by n-peugnet** [comment]
Hi again @albertz, sorry to be insistent but I would really like this PR to be merged. I am currently trying to publish my package on PyPi, but as I am currently using a git url in my `install_requires` it is not letting me upload it.
Do you think that you will have some time to review it and that merging it will be enough to release a version for python3 ?

**Comment by albertz** [comment]
Sorry for the late reply.
This looks good from a first glance. I will just merge it in now.
(Btw, a bit meta: if anyone of you feel that you want to take responsibility for helping me maintaining this, such as checking other pull requests, doing fixed like these, and maybe more, contact me. I can give you direct push access to the repo. I'm currently too busy to be really active here.)

**Comment by albertz** [comment]
As a follow up, e.g. check the Travis tests, why they fail currently.

**Comment by albertz** [comment]
@n-peugnet You are referring to a separate branch, right? Maybe you can create a separate pull request for that?

**Comment by n-peugnet** [comment]
> @n-peugnet You are referring to a separate branch, right? Maybe you can create a separate pull request for that?

Yes I added a commit to fix travis tests on a separated branch. I will do a pr right now

**Pull request merged**
